config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :uploads
  resources :documents do
    collection do
      get :search
    end
  end

  get '/documents/search', to: 'documents#search', as: 'document_search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  include ActiveModel::Conversion

  has_one_attached :file_upload

  attr_accessor :tags

  validates_presence_of :name
  validates_presence_of :account_id
  validates_presence_of :file_upload

  def size
    file_upload.attached? ? self.file_upload.blob.byte_size : 0
  end

  def display_size
    file_upload.attached? ? number_to_human_size(self.file_upload.blob.byte_size) : number_to_human_size(0)
  end

  def mime_type
    file_upload.attached? ? self.file_upload.blob.content_type : "No file"
  end

  def fetch_document_tags
    document_uuid = self.uuid
    tags_from_filely = FilelyApi::Document::Request.get_document_tags(document_uuid)
    unless tags_from_filely == "null" || tags_from_filely.nil?
      parsed_tags = JSON.parse(tags_from_filely)
      parsed_tags.map! { |tag| tag.strip.downcase.tr("_", " ") }
    end
    parsed_tags.present? ? parsed_tags : []
  end

  def fetch_document_metadata
    document_uuid = self.uuid
    metadata_from_filely = FilelyApi::Document::Request.get_document_metadata(document_uuid)
    unless metadata_from_filely == "null" || metadata_from_filely.nil?
      parsed_metadata = JSON.parse(metadata_from_filely)
      parsed_metadata.each { |k, v| parsed_metadata[k] = v.tr("_", " ").titleize }

      self.account_id = parsed_metadata["account_id"]
      self.file_owner = parsed_metadata["file_owner"]
      self.save!
    end
  end

  def post_document
    api_document = FilelyApi::Document.new(self)
    api_document.post_to_filely
  end

  def post_document_updates
    #TODO: so bad... need to check which attr changed...
    FilelyApi::Document::Request.update_document_name(self)
    FilelyApi::Document::Request.update_document_tags(self)
    FilelyApi::Document::Request.update_document_mime_type(self)
    FilelyApi::Document::Request.update_document_size(self)
    FilelyApi::Document::Request.update_document_metadata(self)
  end

  def self.fetch_all_tags
    FilelyApi::Document::Request.get_all_available_tags
  end

  def self.search_by_tags(tags)
    FilelyApi::Document::Request.search_documents_by_tags(tags)
  end

  def self.search_by_metadata(metadata)
    FilelyApi::Document::Request.search_documents_by_metadata(metadata)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  def search
    # so gross
    return unless params[:tags] || params[:metadata]
    tags = params[:tags]
    metadata = params[:metadata]

    if params[:tags].all?(&:present?)
      @documents = Document.search_by_tags(tags)
    elsif params[:metadata].all?(&:present?)
      @documents = Document.search_by_metadata(metadata)
    end

    @documents
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @tags = @document.fetch_document_tags || []
    @metadata = @document.fetch_document_metadata
  end

  # GET /documents/new
  def new
    @document = Document.new
    @tags = []
    # TODO: implement when endpoint in Filey
    # all_available_tags = Document.fetch_all_tags
    # @tags = JSON.parse(all_available_tags) || []
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    @tags = @document.fetch_document_tags || []
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    assign_document_tags(params["tags"])
    # saving document for the file_upload.blob information (mime_type, size)
    if @document.save && @document.post_document
    # if @document.post_document
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    if params["tags"]
      assign_document_tags(params["tags"])
    end
    # updating document for the file_upload.blob information (mime_type, size)
    if @document.update(document_params) && @document.post_document_updates
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
      redirect_to documents_url, notice: 'Document was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    def assign_document_tags(document_tags)
      @document.tags = document_tags
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :account_id, :file_upload, :metadata, :file_owner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>
      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-center">
    <div class="field">
      <span class="text-left"><%= form.label :name %></span>
      <%= form.text_field :name, id: :name %>
    </div>
    <div class="field">
      <%= form.label :file_owner %>
      <%= form.text_field :file_owner, id: :file_owner %>
    </div>
    <div class="field">
      <%= form.label :account_id, 'Account ID' %>
      <%= form.text_field :account_id, id: :account_id %>
    </div>
  </div>
  <div class="text-center">
    <div class="tag-search justify-content-center">
      <%= select_tag 'tags[]', options_for_select(@tags || [], :selected => @tags || []), multiple: true, class: "document-tag-selection", id: "document-tags" %>
    </div>
  </div>
  <% if @document.file_upload.attached? %>
    <div class="text-center">
      <div class="option-links">
        <%= link_to 'View', polymorphic_url(document.file_upload)  %> |
        <%= link_to 'Download', rails_blob_path(document.file_upload, disposition: :attachment) %> |
        <span id="new-document"><%= link_to 'Upload New', :remote => :true %></span>
      </div>
    </div>
    <div class="text-center edit-file-upload" style="display:none;">
      <div class="field file-upload" id="file-upload-field">
        <%= form.file_field :file_upload, id: :file_upload %>
      </div>
    </div>
  <% else %>
    <div class="text-center">
      <div class="field file-upload" id="file-upload-field">
        <%= form.file_field :file_upload, id: :file_upload %>
      </div>
    </div>
  <% end %>
  <div class="text-center">
    <div class="submit-button">
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>




<script>
    $(document).ready(function() {
        $('.document-tag-selection').each(function() {
            $(this).select2({
                tags: true,
                tokenSeparators: [','],
                theme: 'bootstrap',
                placeholder: 'Document tags',
            });
        });

        $('#new-document').on("click", function(){
            $('.option-links').hide();
            $('.edit-file-upload').show()
        });
    });
</script>

app/views/documents/edit.html.erb
<div class="row justify-content-center">
  <div class="card border-info edit-card mb-3">
    <div class="card-header doc-header text-center">Editing Document</div>

    <div class="card-body">
      <%= render 'form', document: @document %>
    </div>
  </div>
</div>
<div class="text-center">
  <div class="option-links">
    <%= link_to 'Show', @document %> |
    <%= link_to 'Back', documents_path %>
  </div>
</div>

app/views/documents/index.html.erb
<div class="row justify-content-center">
  <div class="card main-card-style border-info mb-3">
    <div class="card-header doc-header text-center">Documents
      <div class="pull-left">
        <%= link_to search_documents_path do %>
          <i class="fa fa-search"></i>
        <% end %>
      </div>
      <div class="pull-right">
        <%= link_to new_document_path do %>
          <i class="fa fa-plus"></i>
        <% end %>
      </div>
    </div>
    <% if notice %>
      <p id="notice" class="text-center"><%= notice %></p>
    <% end %>
    <div class="card-body">
      <table>
        <thead class="doc-table">
          <tr>
            <th class="doc-header">Name</th>
            <th class="doc-header">File Owner</th>
            <th class="doc-header">Mime type</th>
            <th class="doc-header">Account ID</th>
            <th class="doc-header">Size</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @documents.each do |document| %>
            <tr>
              <td><%= link_to "#{document.name}", document %></td>
              <td><%= document.file_owner %></td>
              <td><%= document.mime_type %></td>
              <td><%= document.account_id %></td>
              <td><%= document.display_size %></td>
              <td>
              <%= link_to document, method: :delete, data: { confirm: 'Are you sure you want to delete this document?' }, remote: true do %>
                <i class="fa fa-trash"></i>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<div class="row justify-content-center">
  <div class="card new-card main-card-style border-info mb-3">
    <div class="card-header doc-header text-center">New Document</div>
    <div class="card-body">
      <%= render 'form', document: @document %>
    </div>
  </div>
</div>
<div class="text-center">
  <div class="option-links">
    <%= link_to 'Back', documents_path %>
  </div>
</div>

app/views/documents/search.html.erb
<div class="row justify-content-center">
  <div class="card main-card-style search-card border-info mb-3">
    <div class="card-header doc-header text-center">Search Documents</div>
    <% if notice %>
      <p id="notice" class="text-center"><%= notice %></p>
    <% end %>
    <div class="card-body">
      <div class="text-center">
        <div class="row document-search">
          <%= form_tag search_documents_path, :method => :get, :class => 'search-form' do %>
            <%= text_field_tag 'tags[]', params[:tags], class: 'tags-field' %><br/>
            (ie: badge, spill, country)<br/>
            <%= submit_tag 'Search By Tag', :class => 'button page-action tags-field-submit', data: {disable_with: 'Please wait'} %>
          <div class="metadata-search" style="margin-top:10px;">
            <%= text_field_tag 'metadata[]', params[:metadata], class: 'metadata-field' %><br/>
            (ie: slimy:punch, file_owner : Alice)<br/>
            <%= submit_tag 'Search By Metadata', :class => 'button page-action metadata-submit', data: {disable_with: 'Please wait'} %>
          </div>
          <div class="text-center">
            <button id="clear-search-data"class="btn btn-link">Clear Search</button>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="text-center">
  <div class="doc-search-results">
    <% if @documents %>
      <% @documents.each do |document| %>
        <li>Name: <%= document["name"] %>, UUID: <%= document["Uuid"] %></li>
      <% end %>
    <% else %>
      <div class="text-center">
        No Document Results
      </div>
    <% end %>
  </div>
</div>
<div class="text-center back-link">
  <%= link_to "Back", documents_path, class: "back-to-index" %>
</div>

<script>
  $("#clear-search-data").on("click", function(){
      $(".tags-field").val("");
      $(".metadata-field").val("")
  });

  $(".tags-field-submit").on("click", function(){
      $(".metadata-field").val("")
  });

  $(".metadata-submit").on("click", function(){
      $(".tags-field").val("");
  });

</script>

app/views/documents/show.html.erb
<div class="row justify-content-center">
  <div class="card main-card-style border-info mb-3">
    <div class="card-header doc-header text-center"><%= @document.name %></div>
    <div class="card-body">
      <div class="text-center">
        <p id="notice"><%= notice %></p>
      </div>
      <p>
        <span class="doc-header"><strong>Assigned Uuid:</strong></span>
          <%= @document.uuid if @document.uuid %>
      </p>
      <p>
        <span class="doc-header" style="margin-bottom:20px;"><strong>Mime type:</strong></span>
        <%= @document.mime_type %>
        <span class="pull-right">
          <span class="doc-header"><strong>Size:</strong></span>
          <%= @document.display_size %>
        </span>
      </p>
      <p>
        <span class="doc-header" style="margin-bottom:20px;"><strong>Account ID:</strong></span>
        <%= @document.account_id %>
        <span class="pull-right">
          <span class="doc-header"><strong>File Owner:</strong></span>
          <%= @document.file_owner %>
        </span>
      </p>
      <p>
        <span class="doc-header"><strong>Tags:</strong></span>
        <%= @tags.to_sentence if @tags %>
      </p>
      <% if @document.file_upload.attached? %>
        <div class="text-center">
          <div class="view-download-options">
            <p class="pull-left"><%= link_to 'View', polymorphic_url(@document.file_upload) %></p>
            <p class="pull-right"><%= link_to 'Download', rails_blob_path(@document.file_upload, disposition: :attachment) %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="text-center">
  <div class="option-links back-link">
    <%= link_to 'Back', documents_path %> |
    <%= link_to 'Edit', edit_document_path %>
  </div>
</div>


<!--  <card class="new-card">-->
<!--    <h2 class="doc-title">New Document</h2>-->
<!--    <card-body>-->

<!--    </card-body>-->
<!--  </card>-->
<!--</div>-->
<!--<div class="text-center">-->
<!--  <div class="option-links back-link">-->
<%#= link_to 'Back', documents_path %>
<!--  </div>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Documentsdemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>